### ISSUE TITLE
Contribute to Apache JMeter your sampler

### ISSUE THREAD

**Issue by pmouawad** [pflb/Jmeter.Plugin.TailSampler#3]
Hello,
I unfortunately don't speak nor read russian so I read througj translation tools your blog which I found very interesting although not clear due to translation.

I would lile to know if you would be interested in contributing this piece of code to Core JMeter which I think could allow testing Ajax in an easier way.

Thanks for your work !
Regards
Philippe M.

**Comment by polarnik** [comment]
Hello, Philippe. Ok. I will try contributing this piece of code to Core JMeter.
